"""Curated demo dataset of ~50 Chicago-area listings (rental + sale).

These are realistic-but-simulated listings used so the product works out of the box.
The same shape is returned by the live SimplyRETS provider (see provider.py), so
swapping in real data requires only setting SIMPLYRETS_* env vars.
"""
from __future__ import annotations

from product.listings.models import Listing

_NEIGHBORHOODS = {
    "Loop": (41.8818, -87.6278, "60601"),
    "River North": (41.8920, -87.6359, "60611"),
    "West Loop": (41.8834, -87.6623, "60607"),
    "South Loop": (41.8613, -87.6268, "60605"),
    "Lakeview": (41.9405, -87.6536, "60657"),
    "Lincoln Park": (41.9214, -87.6500, "60614"),
    "Wicker Park": (41.9082, -87.6770, "60622"),
    "Bucktown": (41.9170, -87.6770, "60647"),
    "Logan Square": (41.9237, -87.7000, "60647"),
    "Andersonville": (41.9800, -87.6670, "60640"),
    "Edgewater": (41.9899, -87.6590, "60660"),
    "Uptown": (41.9657, -87.6550, "60640"),
    "Hyde Park": (41.7943, -87.5900, "60615"),
    "Bronzeville": (41.8310, -87.6200, "60653"),
    "Pilsen": (41.8570, -87.6600, "60608"),
    "Old Town": (41.9106, -87.6307, "60610"),
    "Streeterville": (41.8925, -87.6187, "60611"),
    "Wrigleyville": (41.9490, -87.6540, "60613"),
}


def _img(seed: str) -> str:
    return f"https://picsum.photos/seed/hh{seed}/640/420"


def _entry(
    idx: int,
    listing_type: str,
    property_type: str,
    price: float,
    beds: float,
    baths: float,
    sqft: int,
    hood: str,
    desc: str,
    amenities: list[str],
    pet: bool = False,
    parking: bool = False,
    furnished: bool = False,
    title: str = "",
) -> Listing:
    lat, lng, z = _NEIGHBORHOODS[hood]
    t = "rent" if listing_type == "rent" else "sale"
    if not title:
        verb = "Bright" if idx % 2 else "Renovated"
        room = {1: "1-Bedroom", 1.5: "1-Bed + Den", 2: "2-Bedroom", 2.5: "2-Bed + Den", 3: "3-Bedroom", 4: "4-Bedroom", 0.5: "Studio"}.get(beds, f"{beds}-Bedroom")
        title = f"{verb} {room} {property_type.capitalize()} in {hood}"
    return Listing(
        id=f"CHI-{idx:04d}",
        listing_type=t,
        property_type=property_type,
        title=title,
        price=price,
        beds=beds,
        baths=baths,
        sqft=sqft,
        neighborhood=hood,
        zipcode=z,
        lat=lat,
        lng=lng,
        description=desc,
        amenities=amenities,
        pet_friendly=pet,
        parking=parking,
        furnished=furnished,
        image_url=_img(f"{idx:04d}"),
        source="demo",
        listed_days=(idx * 3) % 40,
    )


# fmt: off
LISTINGS: list[Listing] = [
    # ---- rentals -------------------------------------------------------
    _entry(1, "rent", "apartment", 1800, 1, 1, 720, "Lakeview",
           "Sunny one-bedroom a block from the lakefront path, in-unit laundry and a chef's kitchen with quartz counters.",
           ["in-unit laundry", "dishwasher", "lakefront access"], pet=True),
    _entry(2, "rent", "studio", 1350, 0.5, 1, 480, "Wicker Park",
           "Cozy studio above a boutique coffee shop, perfect for first renters; steps to the Blue Line.",
           ["heat included", "high ceilings", "near el"], pet=True, parking=False),
    _entry(3, "rent", "apartment", 2450, 2, 1, 980, "Lincoln Park",
           "Garden-level 2-bed with private back patio and shared yard. DePaul and the zoo within walking distance.",
           ["backyard", "storage", "dishwasher"], pet=True, parking=True),
    _entry(4, "rent", "apartment", 3200, 2, 2, 1250, "West Loop",
           "Modern two-bed, two-bath in a doorman building with gym and roof deck, one block from Mary Bartelme Park.",
           ["gym", "roof deck", "doorman", "central air"], pet=False, parking=True),
    _entry(5, "rent", "condo", 2900, 1, 1, 880, "River North",
           "High-floor 1-bed with skyline views, luxury amenities: pool, fitness center, concierge.",
           ["pool", "concierge", "gym", "balcony"], pet=True, parking=True),
    _entry(6, "rent", "townhouse", 3600, 3, 2.5, 1600, "Bucktown",
           "Rare 3-bed townhouse rental with attached garage and a fenced dog run.",
           ["garage", "dog run", "hardwood floors"], pet=True, parking=True),
    _entry(7, "rent", "apartment", 1550, 1, 1, 650, "Edgewater",
           "Quiet 1-bed with bay windows and lake glimpses, heat and water included, near Bryn Mawr Red Line.",
           ["heat included", "water included", "near el"], pet=True),
    _entry(8, "rent", "apartment", 2100, 2, 1, 900, "Logan Square",
           "Charming 2-bed in a greystone with original millwork, sunny east exposure, steps from the 606 trail.",
           ["near 606 trail", "hardwood floors", "central air"], pet=True),
    _entry(9, "rent", "apartment", 1750, 1, 1, 700, "Andersonville",
           "One-bed in the heart of Andersonville's dining district; free laundry and bike storage in the basement.",
           ["laundry in building", "bike storage", "dishwasher"], pet=True, parking=True),
    _entry(10, "rent", "studio", 1450, 0.5, 1, 520, "South Loop",
           "Efficient studio with floor-to-ceiling windows near Grant Park and the Museum Campus.",
           ["floor-to-ceiling windows", "gym", "roof deck"], pet=False, parking=False),
    _entry(11, "rent", "apartment", 2350, 2, 1, 1000, "Old Town",
           "Top-floor 2-bed with a private balcony, renovated kitchen, and a fireplace.",
           ["fireplace", "balcony", "renovated kitchen"], pet=True, parking=False),
    _entry(12, "rent", "apartment", 1950, 2, 1, 850, "Uptown",
           "Spacious 2-bed near Montrose harbor with water views from the living room and an updated bath.",
           ["water views", "dishwasher", "central air"], pet=True, parking=True),
    _entry(13, "rent", "apartment", 1200, 1, 1, 600, "Bronzeville",
           "Affordable 1-bed with fresh paint and new flooring, 5 minutes from the Green Line and Metra.",
           ["near metra", "fresh paint", "central heat"], pet=True, parking=True),
    _entry(14, "rent", "apartment", 1650, 1, 1, 680, "Hyde Park",
           "Campus-adjacent 1-bed near the University of Chicago, includes internet and weekly common-area cleaning.",
           ["internet included", "near campus", "laundry in building"], pet=False, parking=False),
    _entry(15, "rent", "apartment", 2300, 2, 2, 1050, "Streeterville",
           "Two-bed two-bath in a full-amenity tower near Navy Pier with 24/7 doorman and valet.",
           ["doorman", "valet", "pool", "gym"], pet=True, parking=True),
    _entry(16, "rent", "condo", 4100, 3, 2, 1700, "West Loop",
           "Corner 3-bed condo rental with floor-to-ceiling glass, chef's kitchen, and deeded parking spot.",
           ["deeded parking", "chef's kitchen", "floor-to-ceiling glass"], pet=True, parking=True),
    _entry(17, "rent", "apartment", 1400, 1, 1, 620, "Pilsen",
           "Artist-friendly 1-bed with exposed brick and a shared roof deck, two blocks from the Pink Line.",
           ["exposed brick", "roof deck", "near el"], pet=True, parking=False),
    _entry(18, "rent", "house", 4200, 4, 3, 2100, "Lincoln Park",
           "Whole-house rental with private yard, 2-car garage, and a finished basement playroom.",
           ["private yard", "2-car garage", "finished basement"], pet=True, parking=True, furnished=False),
    _entry(19, "rent", "apartment", 2800, 2, 1, 1100, "Lakeview",
           "Furnished 2-bed steps from Wrigley Field; ideal for summer leases; utilities included.",
           ["furnished", "utilities included", "near wrigley"], pet=False, parking=False, furnished=True),
    _entry(20, "rent", "apartment", 2050, 1, 1, 780, "Wicker Park",
           "First-floor 1-bed in a vintage courtyard building with a shared garden and bike room.",
           ["courtyard", "garden", "bike room"], pet=True, parking=False),
    _entry(21, "rent", "studio", 1600, 0.5, 1, 550, "River North",
           "Modern studio with Murphy bed and kitchenette, steps from Michigan Avenue shopping.",
           ["kitchenette", "doorman", "gym"], pet=False, parking=True),
    _entry(22, "rent", "apartment", 2600, 2, 2, 1150, "South Loop",
           "Two-bed, two-bath with southern exposure and city views, across from the Field Museum.",
           ["city views", "gym", "roof deck"], pet=True, parking=True),
    _entry(23, "rent", "house", 2400, 3, 2, 1450, "Andersonville",
           "Charming 3-bed single-family rental on a tree-lined street with a porch swing and basement storage.",
           ["porch", "basement storage", "central air"], pet=True, parking=True),
    _entry(24, "rent", "apartment", 1850, 2, 1, 860, "Pilsen",
           "Spacious 2-bed with a walk-in closet and updated kitchen, blocks from a vibrant restaurant strip.",
           ["walk-in closet", "updated kitchen", "laundry in building"], pet=True, parking=True),
    # ---- sales ---------------------------------------------------------
    _entry(25, "sale", "condo", 349000, 2, 2, 1180, "Loop",
           "Rare value in the Loop: renovated 2-bed, 2-bath with a parking space included and low HOA.",
           ["parking included", "renovated", "concierge"], pet=True, parking=True),
    _entry(26, "sale", "condo", 525000, 1, 1, 900, "River North",
           "Investment-grade 1-bed with a deeded parking spot, strong rental history and skyline views.",
           ["deeded parking", "rental history", "pool"], pet=True, parking=True),
    _entry(27, "sale", "townhouse", 620000, 3, 2.5, 1750, "Wicker Park",
           "Newly built 3-bed townhouse with a rooftop deck, attached garage, and 10-year tax incentive.",
           ["rooftop deck", "attached garage", "new construction"], pet=True, parking=True),
    _entry(28, "sale", "condo", 795000, 2, 2, 1400, "West Loop",
           "Premium corner unit in a glass tower with 2 parking spots and a resort-style amenity floor.",
           ["2 parking spots", "amenity floor", "pool"], pet=True, parking=True),
    _entry(29, "sale", "house", 875000, 4, 3.5, 2400, "Lincoln Park",
           "Classic Lincoln Park 4-bed brick home with a chef's kitchen, deck, and a two-car garage.",
           ["chef's kitchen", "deck", "2-car garage"], pet=True, parking=True),
    _entry(30, "sale", "condo", 415000, 2, 2, 1050, "Lakeview",
           "Lakeview 2-bed with east exposure and lake views, one block from the lakefront trail.",
           ["lake views", "lakefront access", "balcony"], pet=True, parking=False),
    _entry(31, "sale", "house", 699000, 3, 2.5, 1900, "Logan Square",
           "Gut-renovated greystone with modern finishes, two bedrooms plus a den, and a private yard.",
           ["private yard", "modern finishes", "hardwood floors"], pet=True, parking=True),
    _entry(32, "sale", "condo", 289000, 1, 1, 760, "Edgewater",
           "First-time buyer favorite: renovated 1-bed with lake glimpses and a strong rental market.",
           ["renovated", "lake glimpses", "laundry in building"], pet=True, parking=True),
    _entry(33, "sale", "house", 825000, 3, 3, 2100, "Bucktown",
           "Architect-designed 3-bed with a dramatic lightwell, roof deck, and a detached 2-car garage.",
           ["roof deck", "lightwell", "detached garage"], pet=True, parking=True),
    _entry(34, "sale", "condo", 655000, 3, 2, 1450, "Streeterville",
           "Three-bed, two-bath in a luxury high-rise with a private balcony facing the lake.",
           ["private balcony", "lake facing", "valet"], pet=True, parking=True),
    _entry(35, "sale", "house", 495000, 3, 2, 1600, "Bronzeville",
           "Beautifully restored Victorian 3-bed with original woodwork, new roof, and a sunny porch.",
           ["original woodwork", "new roof", "porch"], pet=True, parking=True),
    _entry(36, "sale", "condo", 375000, 2, 2, 1000, "Hyde Park",
           "Two-bed, two-bath condo in a pre-war building near the lake, with a library room and garage access.",
           ["pre-war", "library room", "garage access"], pet=True, parking=True),
    _entry(37, "sale", "townhouse", 585000, 3, 2.5, 1650, "South Loop",
           "Corner townhouse with a garage, finished basement, and private rooftop terrace.",
           ["rooftop terrace", "finished basement", "garage"], pet=True, parking=True),
    _entry(38, "sale", "condo", 740000, 2, 2, 1300, "Old Town",
           "Sun-drenched 2-bed on a quiet Old Town street with a wood-burning fireplace and private deck.",
           ["fireplace", "private deck", "in-unit laundry"], pet=True, parking=True),
    _entry(39, "sale", "house", 575000, 3, 2, 1500, "Andersonville",
           "Solid Andersonville 3-bed with a fenced yard, updated kitchen, and basement storage.",
           ["fenced yard", "updated kitchen", "basement"], pet=True, parking=True),
    _entry(40, "sale", "condo", 485000, 2, 1, 1100, "Wrigleyville",
           "Charming 2-bed in a boutique walk-up, one block to Wrigley Field and the Addison Red Line.",
           ["near wrigley", "near el", "fresh paint"], pet=True, parking=False),
    _entry(41, "sale", "house", 925000, 4, 3.5, 2600, "Lakeview",
           "Full brick 4-bed on a quiet cul-de-sac with a two-car garage and a huge fenced yard.",
           ["cul-de-sac", "2-car garage", "huge yard"], pet=True, parking=True),
    _entry(42, "sale", "condo", 645000, 2, 2, 1250, "West Loop",
           "Two-bed, two-bath with an open chef's kitchen and walk-in closets, one block from the green line.",
           ["chef's kitchen", "walk-in closets", "near el"], pet=True, parking=True),
    _entry(43, "sale", "house", 485000, 3, 1.5, 1350, "Pilsen",
           "Incredible Pilsen bungalow with a walkable art district at your doorstep and a deep backyard.",
           ["bungalow", "deep backyard", "hardwood floors"], pet=True, parking=True),
    _entry(44, "sale", "condo", 330000, 1, 1, 820, "Uptown",
           "Affordable 1-bed with lake views from the balcony and one of the lowest HOA fees in the neighborhood.",
           ["lake views", "balcony", "low hoa"], pet=True, parking=True),
    _entry(45, "sale", "house", 549000, 3, 2, 1700, "Hyde Park",
           "Historic 3-bed with crown molding, an updated kitchen, and a lush garden lot near the lake.",
           ["crown molding", "garden lot", "updated kitchen"], pet=True, parking=True),
    _entry(46, "sale", "condo", 715000, 2, 2.5, 1550, "River North",
           "Double-level penthouse-style 2-bed with a spiral stair and wrap terrace.",
           ["spiral stair", "wrap terrace", "concierge"], pet=True, parking=True),
    _entry(47, "sale", "house", 749000, 4, 3, 2000, "Logan Square",
           "Four-bed with a finished attic studio and an oversized yard, priced for the boulevard.",
           ["attic studio", "oversized yard", "central air"], pet=True, parking=True),
    _entry(48, "sale", "condo", 445000, 2, 2, 1150, "Edgewater",
           "Rare 2-bed, 2-bath with lake views, a balcony, and a heated indoor parking spot.",
           ["heated parking", "lake views", "balcony"], pet=True, parking=True),
]
# fmt: on
