"""Curated demo dataset of ~48 Irish rental listings.

IMPORTANT: the Property Price Register covers SALES ONLY — there is no public
rental register. These rentals are realistic-but-simulated demo data used so the
product works out of the box; they are labelled `demo` in the product. Live sales
data comes from the PPR providers (see ppr.py). Swapping in a real rental feed
requires only adding a provider that implements ListingsProvider.
"""
from __future__ import annotations

from product.listings.models import Listing


def _entry(
    idx: int,
    property_type: str,
    price: float,
    beds: float,
    baths: float,
    sqft: int,
    county: str,
    hood: str,
    city: str,
    eircode: str,
    lat: float,
    lng: float,
    desc: str,
    amenities: list[str],
    pet: bool = False,
    parking: bool = False,
    furnished: bool = False,
) -> Listing:
    room = {0.5: "Studio", 1: "1-Bedroom", 2: "2-Bedroom", 3: "3-Bedroom", 4: "4-Bedroom"}.get(beds, f"{beds}-Bedroom")
    verb = "Bright" if idx % 2 else "Modern"
    title = f"{verb} {room} {property_type.capitalize()} in {hood}"
    return Listing(
        id=f"IE-{idx:04d}",
        listing_type="rent",
        property_type=property_type,
        title=title,
        price=price,
        county=county,
        beds=beds,
        baths=baths,
        sqft=sqft,
        neighborhood=hood,
        city=city,
        eircode=eircode,
        lat=lat,
        lng=lng,
        description=desc,
        amenities=amenities,
        pet_friendly=pet,
        parking=parking,
        furnished=furnished,
        image_url=f"https://picsum.photos/seed/ie{idx:04d}/640/420",
        source="demo",
        listed_days=(idx * 3) % 40,
    )


# fmt: off
LISTINGS: list[Listing] = [
    # ---- Dublin ---------------------------------------------------------
    _entry(1, "apartment", 2200, 1, 1, 620, "Dublin", "Ranelagh", "Dublin 6", "D06", 53.3259, -6.2541,
           "Bright one-bed in Ranelagh village, minutes to the Luas Green Line, in-unit laundry and a modern kitchen.",
           ["in-unit laundry", "dishwasher", "near Luas"], pet=True),
    _entry(2, "studio", 1600, 0.5, 1, 380, "Dublin", "Rathmines", "Dublin 6", "D06", 53.3200, -6.2620,
           "Cosy studio above a café on Rathmines Main Street — perfect for a first rental, all bills included.",
           ["bills included", "high ceilings", "furnished"], pet=False, furnished=True),
    _entry(3, "apartment", 2450, 2, 1, 780, "Dublin", "Phibsboro", "Dublin 7", "D07", 53.3600, -6.2730,
           "Two-bed garden flat in Phibsboro with a private patio, minutes to the Luas and the Royal Canal.",
           ["private patio", "garden", "dishwasher"], pet=True, parking=True),
    _entry(4, "apartment", 3200, 2, 2, 980, "Dublin", "Ballsbridge", "Dublin 4", "D04", 53.3320, -6.2320,
           "Executive two-bed, two-bath in a doorman block on a leafy D4 square, walk to the RDS and Aviva.",
           ["doorman", "gym", "concierge", "central heating"], pet=False, parking=True),
    _entry(5, "apartment", 2800, 1, 1, 650, "Dublin", "Dún Laoghaire", "Co. Dublin", "A96", 53.2930, -6.1340,
           "Seafront one-bed a minute from Dún Laoghaire harbour, with sea views and a residents' gym.",
           ["sea views", "gym", "near DART"], pet=True, parking=True),
    _entry(6, "house", 3600, 3, 2, 1200, "Dublin", "Clontarf", "Dublin 3", "D03", 53.3650, -6.2100,
           "Family 3-bed redbrick with a south-facing garden, driveway, and the seafront promenade nearby.",
           ["south-facing garden", "driveway", "near seafront"], pet=True, parking=True),
    _entry(7, "apartment", 1900, 1, 1, 540, "Dublin", "Smithfield", "Dublin 7", "D07", 53.3480, -6.2780,
           "One-bed loft-style apartment in Smithfield with floor-to-ceiling windows, two minutes to the Luas Red Line.",
           ["loft-style", "floor-to-ceiling windows", "near Luas"], pet=False, parking=False),
    _entry(8, "apartment", 2100, 2, 1, 700, "Dublin", "Dublin 8", "Dublin 8", "D08", 53.3410, -6.2810,
           "Renovated 2-bed in Dublin 8's Liberties, exposed brick, near the Coombe and the Digital Hub.",
           ["exposed brick", "renovated", "laundry in building"], pet=True, parking=False),
    _entry(9, "house", 4300, 3, 2, 1400, "Dublin", "Malahide", "Co. Dublin", "K36", 53.4508, -6.1544,
           "Stunning 3-bed detached in Malahide with a large garden, home office, and garage, close to the DART and marina.",
           ["garden", "home office", "garage", "near DART"], pet=True, parking=True),
    _entry(10, "apartment", 1750, 1, 1, 520, "Dublin", "Stoneybatter", "Dublin 7", "D07", 53.3510, -6.2820,
           "Charmer one-bed in Stoneybatter village, close to cafés, the Phoenix Park and the Luas.",
           ["near Phoenix Park", "dishwasher", "high ceilings"], pet=True, parking=False),
    _entry(11, "apartment", 2400, 2, 2, 820, "Dublin", "Grand Canal Dock", "Dublin 2", "D02", 53.3400, -6.2390,
           "Two-bed, two-bath in the Grand Canal Dock tech hub, doorman building with gym and river views.",
           ["doorman", "gym", "river views"], pet=True, parking=True),
    _entry(12, "apartment", 1850, 1, 1, 560, "Dublin", "Swords", "Co. Dublin", "K67", 53.4590, -6.2180,
           "Convenient one-bed in Swords, minutes to the M50 and Dublin Airport — ideal for commuters.",
           ["near M50", "near airport", "parking"], pet=True, parking=True),
    _entry(13, "apartment", 2650, 2, 1, 760, "Dublin", "Portobello", "Dublin 8", "D08", 53.3310, -6.2650,
           "Top-floor 2-bed on the Grand Canal with a private balcony, walk-in closet, and lift access.",
           ["balcony", "walk-in closet", "lift access"], pet=False, parking=True),
    _entry(14, "apartment", 1550, 1, 1, 480, "Dublin", "Tallaght", "Dublin 24", "D24", 53.2850, -6.3730,
           "Affordable one-bed near Tallaght Luas and the Square, with fibre broadband included.",
           ["fibre broadband included", "near Luas", "laundry in building"], pet=True, parking=True),
    _entry(15, "apartment", 2500, 1, 1, 620, "Dublin", "Howth", "Co. Dublin", "D13", 53.3870, -6.0650,
           "One-bed with sea views in Howth village, a walk from the cliffs, harbour and DART station.",
           ["sea views", "near DART", "balcony"], pet=True, parking=True),
    _entry(16, "house", 3400, 3, 1.5, 1100, "Dublin", "Blanchardstown", "Dublin 15", "D15", 53.3850, -6.3830,
           "Three-bed semi-d with a private driveway and rear garden in a quiet estate, close to the Luas and M50.",
           ["rear garden", "driveway", "near M50"], pet=True, parking=True),
    _entry(17, "apartment", 2350, 2, 2, 850, "Dublin", "Donnybrook", "Dublin 4", "D04", 53.3240, -6.2430,
           "Two-bed, two-bath in a new-build scheme in Donnybrook, BER A rated with underfloor heating.",
           ["BER A", "underfloor heating", "gym"], pet=True, parking=True),
    _entry(18, "apartment", 2050, 1, 1, 600, "Dublin", "Drumcondra", "Dublin 9", "D09", 53.3730, -6.2580,
           "One-bed within walking distance of DCU, with a shared garden and on-street parking nearby.",
           ["near DCU", "shared garden", "storage"], pet=False, parking=False),
    _entry(19, "apartment", 2700, 2, 2, 900, "Dublin", "Docklands", "Dublin 1", "D01", 53.3490, -6.2400,
           "Contemporary 2-bed in the IFSC/Docklands with city views, concierge and a residents' lounge.",
           ["concierge", "city views", "residents lounge"], pet=True, parking=True),
    _entry(20, "house", 3950, 4, 2, 1500, "Dublin", "Castleknock", "Dublin 15", "D15", 53.3740, -6.3620,
           "Bright 4-bed detached in Castleknock with a large garden, double garage and great schools nearby.",
           ["large garden", "double garage", "near schools"], pet=True, parking=True),
    _entry(21, "studio", 1700, 0.5, 1, 420, "Dublin", "City Centre", "Dublin 1", "D01", 53.3498, -6.2603,
           "Sleek studio off O'Connell Street with a kitchenette and lift access, ideal for city workers.",
           ["kitchenette", "lift access", "city centre"], pet=False, parking=False),
    _entry(22, "apartment", 2250, 1, 1, 640, "Dublin", "Blackrock", "Co. Dublin", "A94", 53.3020, -6.1830,
           "One-bed in Blackrock village, minutes to the DART, sea and the Q-Park for commuters.",
           ["near DART", "near sea", "in-unit laundry"], pet=True, parking=True),
    _entry(23, "apartment", 2600, 2, 1, 800, "Dublin", "Rathgar", "Dublin 6", "D06", 53.3090, -6.2780,
           "Two-bed in Rathgar with original fireplaces, off-street parking and a sunny rear garden.",
           ["fireplaces", "off-street parking", "rear garden"], pet=True, parking=True),
    _entry(24, "apartment", 2000, 1, 1, 580, "Dublin", "Fairview", "Dublin 3", "D03", 53.3650, -6.2390,
           "One-bed with a balcony overlooking Fairview Park, a short walk to the DART and city centre buses.",
           ["balcony", "park views", "near DART"], pet=True, parking=False),
    # ---- Cork -----------------------------------------------------------
    _entry(25, "apartment", 1650, 1, 1, 560, "Cork", "Cork City Centre", "Cork", "T12", 51.8985, -8.4756,
           "Central one-bed minutes from St Patrick's Street and the English Market, with secure entry.",
           ["secure entry", "city centre", "dishwasher"], pet=False, parking=False),
    _entry(26, "apartment", 1950, 2, 1, 760, "Cork", "Douglas", "Cork", "T12", 51.8760, -8.4370,
           "Two-bed in Douglas with a balcony, residents' gym and easy access to the South Ring Road.",
           ["balcony", "gym", "near South Ring"], pet=True, parking=True),
    _entry(27, "house", 2400, 3, 1.5, 1050, "Cork", "Blackrock", "Cork", "T12", 51.8970, -8.4070,
           "Three-bed semi-d in Blackrock village with a driveway, rear garden and superb primary schools.",
           ["driveway", "rear garden", "near schools"], pet=True, parking=True),
    _entry(28, "apartment", 1750, 1, 1, 540, "Cork", "Ballincollig", "Cork", "P43", 51.8870, -8.5820,
           "One-bed close to Ballincollig Regional Park and the Lee Fields, with allocated parking.",
           ["allocated parking", "near park", "storage"], pet=True, parking=True),
    _entry(29, "apartment", 2100, 2, 2, 800, "Cork", "Wilton", "Cork", "T12", 51.8870, -8.5300,
           "Two-bed, two-bath near Wilton Shopping Centre and CUH, with a gym and concierge.",
           ["gym", "concierge", "near hospital"], pet=False, parking=True),
    _entry(30, "house", 2700, 3, 2, 1150, "Cork", "Carrigaline", "Cork", "P43", 51.8150, -8.3940,
           "Modern 3-bed detached in Carrigaline with a large garden, driveway and a bright kitchen diner.",
           ["large garden", "driveway", "kitchen diner"], pet=True, parking=True),
    # ---- Galway ---------------------------------------------------------
    _entry(31, "apartment", 1750, 1, 1, 560, "Galway", "Galway City Centre", "Galway", "H91", 53.2707, -9.0568,
           "One-bed in the heart of Galway's Latin Quarter, steps from the Corrib and Shop Street.",
           ["city centre", "near river", "secure entry"], pet=False, parking=False),
    _entry(32, "apartment", 1900, 2, 1, 700, "Galway", "Salthill", "Galway", "H91", 53.2610, -9.0870,
           "Two-bed with sea views on the Salthill promenade, beach on your doorstep and a private balcony.",
           ["sea views", "balcony", "near beach"], pet=True, parking=True),
    _entry(33, "house", 2400, 3, 2, 1100, "Galway", "Knocknacarra", "Galway", "H91", 53.2770, -9.0860,
           "Three-bed semi-d in Knocknacarra with a rear garden, driveway and quick access to the city.",
           ["rear garden", "driveway", "near schools"], pet=True, parking=True),
    _entry(34, "apartment", 1650, 1, 1, 520, "Galway", "Renmore", "Galway", "H91", 53.2780, -9.0350,
           "One-bed close to NUIG and GMIT, with a shared garden and on-site parking.",
           ["near universities", "shared garden", "parking"], pet=True, parking=True),
    _entry(35, "apartment", 2100, 2, 2, 780, "Galway", "Galway City Centre", "Galway", "H91", 53.2700, -9.0600,
           "Two-bed, two-bath riverside apartment with a balcony over the Corrib, lift access and gym.",
           ["riverside", "balcony", "gym"], pet=False, parking=True),
    _entry(36, "house", 2250, 3, 1.5, 1000, "Galway", "Rahoon", "Galway", "H91", 53.2820, -9.0720,
           "Three-bed with a good-sized garden, garage and quiet cul-de-sac location, 10 minutes to town.",
           ["garden", "garage", "cul-de-sac"], pet=True, parking=True),
    # ---- Limerick -------------------------------------------------------
    _entry(37, "apartment", 1450, 1, 1, 540, "Limerick", "Limerick City Centre", "Limerick", "V94", 52.6638, -8.6267,
           "Affordable one-bed in the city centre, minutes to the Milk Market and UL shuttle stop.",
           ["city centre", "near market", "secure entry"], pet=False, parking=False),
    _entry(38, "apartment", 1700, 2, 1, 720, "Limerick", "Castletroy", "Limerick", "V94", 52.6690, -8.5630,
           "Two-bed in Castletroy, a short walk to UL campus, with parking and a residents' gym.",
           ["near UL", "gym", "parking"], pet=True, parking=True),
    _entry(39, "house", 1850, 3, 1.5, 980, "Limerick", "Dooradoyle", "Limerick", "V94", 52.6300, -8.6480,
           "Three-bed semi-d in Dooradoyle with a rear garden, driveway and proximity to the Crescent Court.",
           ["rear garden", "driveway", "near retail park"], pet=True, parking=True),
    _entry(40, "apartment", 1550, 1, 1, 560, "Limerick", "Raheen", "Limerick", "V94", 52.6150, -8.6600,
           "One-bed near Raheen Business Park, ideal for engineers and commuters, with allocated parking.",
           ["allocated parking", "near business park", "fibre broadband"], pet=True, parking=True),
    _entry(41, "apartment", 1950, 2, 2, 850, "Limerick", "Limerick City Centre", "Limerick", "V94", 52.6610, -8.6300,
           "Two-bed, two-bath riverside apartment overlooking the Shannon with a balcony and gym.",
           ["riverside", "balcony", "gym"], pet=False, parking=True),
    _entry(42, "house", 1750, 3, 1, 900, "Limerick", "Annacotty", "Limerick", "V94", 52.6780, -8.5530,
           "Three-bed in Annacotty village with a small garden, close to the M7 for Dublin commutes.",
           ["small garden", "near M7", "storage"], pet=True, parking=True),
    # ---- Waterford ------------------------------------------------------
    _entry(43, "apartment", 1250, 1, 1, 500, "Waterford", "Waterford City Centre", "Waterford", "X91", 52.2593, -7.1101,
           "Budget-friendly one-bed in Waterford city, steps from the Quay, bus station and restaurants.",
           ["city centre", "near bus", "secure entry"], pet=False, parking=False),
    _entry(44, "apartment", 1500, 2, 1, 680, "Waterford", "Ferrybank", "Waterford", "X91", 52.2650, -7.1220,
           "Two-bed with river views across the Suir, balcony and easy parking, five minutes from the city.",
           ["river views", "balcony", "parking"], pet=True, parking=True),
    _entry(45, "house", 1700, 3, 1.5, 950, "Waterford", "Tramore", "Waterford", "X91", 52.1620, -7.1530,
           "Three-bed in Tramore with a sunny garden, a short stroll to the beach and the amusement park.",
           ["sunny garden", "near beach", "driveway"], pet=True, parking=True),
    _entry(46, "apartment", 1350, 1, 1, 520, "Waterford", "Waterford City Centre", "Waterford", "X91", 52.2600, -7.1150,
           "One-bed apartment above shops on The Mall, gas heating included, close to SETU campus.",
           ["near SETU", "heating included", "city centre"], pet=True, parking=False),
    _entry(47, "house", 1850, 3, 2, 1050, "Waterford", "Dunmore East", "Waterford", "X91", 52.1500, -6.9900,
           "Three-bed coastal house in Dunmore East with sea views and a garden, a haven for weekenders.",
           ["sea views", "garden", "coastal"], pet=True, parking=True),
    _entry(48, "apartment", 1600, 2, 1, 700, "Waterford", "Ardkeen", "Waterford", "X91", 52.2540, -7.0950,
           "Two-bed near Ardkeen Village, minutes to the hospital and park, with balcony and storage.",
           ["near hospital", "balcony", "storage"], pet=True, parking=True),
]
# fmt: on
